### PR TITLE
Bump version number and add fabio.

### PR DESCRIPTION
**Pull request by danielballan**
**DO NOT MERGE UNTIL WE ARE READY TO RELEASE 2018-1.1.** All
additions to 2018-1.1 should be added on this PR. Merging will
trigger the builder.

This PR includes commits from #245. #245 should be merged first.

### CODE REVIEW

**Comment by tacaswell** [comment]
See discussion https://github.com/NSLS-II/lightsource2-recipes/pull/239#issuecomment-358300767 for apparent issue with '-' in versions.

**Comment by jrmlhermitte** [comment]
looks good. I approve. @tacaswell ?

**Comment by danielballan** [comment]
Looks like this should wait until we decide between `_` and `C`. I have no strong opinion but we should be consistent.

**Comment by mrakitin** [comment]
+1 for `_` as in https://github.com/NSLS-II/lightsource2-recipes/pull/245#discussion_r162112891.

**Comment by mrakitin** [comment]
Other changes look good to me.

**Comment by mrakitin** [comment]
@danielballan, I hoped it was fine to merge it. Please revert if it's still early.

**Comment by danielballan** [comment]
Not a big deal, but I had intended this not to be merged until _all_ the packages for 2018-1.1 were set and added to this PR. Now that it has been merged, the builder has created 2018-1.1 packages, and reverting this won't change that.

**Comment by mrakitin** [comment]
Sorry again, was in a hurry. Will think twice next time.

**Comment by danielballan** [comment]
No worries. My proposed system was an odd one and should probably be re-thought anyway.

**Pull request merged**
