### PR TITLE
Fixed analysis metapackage

### PR DESCRIPTION
**Pull request by jrmlhermitte**
fix to analysis metapackage
@danielballan

### CODE REVIEW

**Comment by danielballan** [comment]
Did the original merge supercede the actual 04-id-isr-collection? Better check that we don't have a packaged named 04-id-isr-collection that is actually 04-id-isr-analysis.

**Comment by danielballan** [comment]
I see. Well, the way to do it would be to delete the bad file using the web UI, and then increase the build number the recipe by 1 so that the auto-builder re-processes it.

**Comment by jrmlhermitte** [comment]
thanks. i dont think it's necessary this time since the meta.yaml is the same. the folder name is all that was different and that should have no consequence on the package. correct?

thanks for this info though, it is very useful

**Comment by danielballan** [comment]
Agreed.

**Pull request merged**
