### PR TITLE
Fix tifffile recipe

### PR DESCRIPTION
**Pull request by mrakitin**
The following message appears when `bsui` starts:
```py
/opt/conda_envs/collection-2019-2.0-csx/lib/python3.6/site-packages/tifffile/tifffile.py:298: UserWarning: ImportError: No module named '_tifffile'. Loading of some compressed images will be very slow. Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "ImportError: No module named '_tifffile'. "
```
According to @CJ-Wright, `{{ pin_compatible('numpy') }}` can only be in the `run` or `test` section of the recipe, but not in the `built` one.

### CODE REVIEW

**Comment by mrakitin** [comment]
Self-merging to see if it builds, so we can test the new package.

**Comment by danielballan** [comment]
Good to know. Thanks, @CJ-Wright.

**Comment by CJ-Wright** [comment]
https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions

**Comment by leofang** [comment]
> https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions

@CJ-Wright I wish the fact that `pin_compatible` cannot be used in the `build` section is clearly documented in the Conda-build document...It was not obvious from the way it is stated.

**Comment by CJ-Wright** [comment]
Ideally conda would yell at you if it detected that you did that, but I'm not ready to put up a PR to that effect.

**Pull request merged**
