### PR TITLE
Auto cf

### LINKED ISSUE #255: Auto pull recipes from conda forge
It might be nice to have a system which trolls through conda forge for new versions of the recipes.

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #255 
@jrmlhermitte @danielballan 
I think this should work, it worked on my local. Once everyone is happy with this they should:
1. turn the `totally_not_a_travis.yaml` file into a valid `.travis.yaml`
1. Run doctr to get the keys setup properly
1. Figure out which branch to push to so we don't end up with recursive things (one may consider separating the branches/repos which hold the recipes for general PRing and the branches/repos which hold the recipes for the internal server to read/build) (one could also consider putting this script in a separate repo, cloning this repo, updating everything, and then pushing back to this repo.
1. Turn on travis

### CODE REVIEW

**Comment by tacaswell** [comment]
Can this be done with plain python or plain bash?

**Comment by CJ-Wright** [comment]
Probably, PRs welcome.

**Comment by danielballan** [comment]
We have no xonsh users on staff, so we are not really able to maintain this as is. As you speak xonsh, would you be willing to translate it for us?

**Comment by CJ-Wright** [comment]
I won't be able to translate this right now. I may be able to later in the week. If there is some interest in learning xonsh here are the docs: 
- http://xon.sh/ 
- http://xon.sh/tutorial.html 

Xonsh is fairly intuitive, the deps are very light, and the devs are very responsive.

**Comment by danielballan** [comment]
I really love xonsh; I hope it takes over the world; I agree with @tacaswell that this is not a good enough reason to add yet-another-thing that some onboarding member of staff would have to learn in order to maintain our already-complex build stack.

Sorry for the thanks-for-the-milk-can-we-have-a-cookie nature of this request, but some help translating this would be great when you have the time!

**Comment by CJ-Wright** [comment]
@mrakitin this is the PR with auto conda-forge updating.

**Comment by mrakitin** [comment]
@CJ-Wright, thanks, but I'm not sure how we can use it with our current building approach. Can you explain?

**Comment by CJ-Wright** [comment]
This would issue PRs into lightsource2-recipes with updates from the conda-forge recipes which are in lightsource2. Those PRs could be merged and then building would continue as normal. The main benefit of this is that new versions/updates to recipes from the community would be PRed over to lightsource2-recipes automatically.

A potential extension of this would be to build a graph and check that all deps are on lightsource2-recipes or defaults, but that could be done later.

**Pull request closed without merging**
