### PR TITLE
Update

### PR DESCRIPTION
**Pull request by licode**
waiting for ophyd's new version.

### CODE REVIEW

**Comment by licode** [comment]
ready to go. @tacaswell ?

**Comment by tacaswell** [comment]
I think these recipes will fail to build due to sha failures?

**Comment by licode** [comment]
updated.

**Comment by tacaswell** [comment]
Did you mean to commit those changes to the scripts?

**Comment by licode** [comment]
I think this should be ready to go. I tested the build process which works fine.

**Pull request merged**
