### PR TITLE
Add metapackages for collection, analysis.

### PR DESCRIPTION
**Pull request by danielballan**
This PR adds metapackages, similar to conda's `environment.yml` idea but with slightly different feature set. We tried this once before and abandoned it. Maybe it will stick this time.

* The `analysis` metapackage contains most of our stuff, including bluesky because the callbacks are useful on saved data.
* The `collection` metapackage depends on the `analysis` one, and it adds ophyd and pyolog.
* The version scheme is not semantic versioning: it is the date plus a micro version for corrections (e.g., `2016-09-29.0`.

### CODE REVIEW

**Comment by tacaswell** [comment]
Maybe a terser date? `16Q4.0` ?

**Comment by danielballan** [comment]
That was my impulse (that's what we did last time) but yesterday you said, "The correct way to do this is to specify the whole date."

**Comment by tacaswell** [comment]
I need to get my memory checked apparently.

**Comment by danielballan** [comment]
:- D

For real, I can see the case either way. A "quarter" is prettier; a date is in some ways "easier" because it's completely clear.

**Comment by danielballan** [comment]
Feel free to push to my branch and merge.

**Comment by ericdill** [comment]
These recipes also exist in recipes-tag. [collection] (https://github.com/NSLS-II/lightsource2-recipes/blob/master/recipes-tag/collection/meta.yaml) and [analysis] (https://github.com/NSLS-II/lightsource2-recipes/blob/master/recipes-tag/analysis/meta.yaml)

Probably want to remove them from there to avoid future confusion

**Pull request merged**
