### PR TITLE
Xpd 2018 1

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by tacaswell** [comment]
do you want this merged asap?

**Comment by CJ-Wright** [comment]
Sure, there will be another one for xpdAcq, xpdAn, and SHED in the very near future

**Comment by CJ-Wright** [comment]
Or you can wait for those to come in.

**Comment by tacaswell** [comment]
might as well get the contraption spinning sooner rather than later.  Branches and PRs are cheap

**Pull request merged**
