### PR TITLE
add oscars

### PR DESCRIPTION
**Pull request by licode**
local build runs ok. https://github.com/NSLS-II/lightsource2-recipes/issues/205#issuecomment-335983026

### CODE REVIEW

**Comment by licode** [comment]
@danielballan

**Comment by licode** [comment]
@dhidas , can you also check if any dependency is missing.

**Comment by dhidas** [comment]
This seems ok.  mpi4py is not required so you can leave it out you like.  Unless someone has a networked cluster I believe the internal multi-threadding is better anyways.

If you're compiling it you'll need a c++11 compliant compiler, but maybe you are pulling the manylinux1 binaries?  These at the moment are the same (for linux only).  In the future when I figure out how to package the binary for a pseudo-manylinux the binary will contain libraries which can only be made with nvcc, which I guess is difficult with conda at the moment...

**Comment by licode** [comment]
I think I will leave mpi4pi there just in case it is used. I follow setup.py where c++11 compiler is defined for linux. Let's give it a try, and see if it works ok.

**Comment by licode** [comment]
The conda package oscars will be shown at https://anaconda.org/lightsource2-tag/ once it is ready, so you can try
```
conda install oscars -c lightsource2-tag
```

or you can try the following if at beamline machine
```
conda install oscars -c nsls2-tag
```

**Comment by dhidas** [comment]
Great!  And a question.. It will show up on notebook.nsns2 ?

**Comment by licode** [comment]
We need to re-install it first. But you can test it on your local machine first when the package is ready.

**Comment by licode** [comment]
The package is ready to use https://anaconda.org/lightsource2-tag/oscars

**Comment by stuartcampbell** [comment]
Awesome @licode

**Comment by dhidas** [comment]
Tested and it does work!

Also, does this automatically pick up the master branch, or release, or something from github?  I notice that my v2.0.2 is already there...

Many thanks, this is really great.

**Comment by tacaswell** [comment]
The tag to use is set https://github.com/NSLS-II/lightsource2-recipes/blob/master/recipes-tag/oscars/meta.yaml#L2

When you do a new release just open a PR adjusting that number.

**Pull request merged**
