### PR TITLE
Add missed dep in xpdacq recipe.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by licode** [comment]
any change on version number and build number?

**Comment by danielballan** [comment]
Wait wait -- your last comment about bumping the build number was correct. I just didn't get around to responding/fixing yet. Did merging this PR overwrite the old build or just fail?

**Comment by licode** [comment]
Whoops. It will not build. Do you want to change something else or just the build number?

**Comment by danielballan** [comment]
Just the build number.

**Comment by licode** [comment]
https://github.com/NSLS-II/lightsource2-recipes/pull/179

**Pull request merged**
