### PR TITLE
xpd version bump

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Attn: @jrmlhermitte

**Comment by jrmlhermitte** [comment]
looks good to me. merging

**Comment by CJ-Wright** [comment]
Please let me know when you deploy at the beamline

**Comment by jrmlhermitte** [comment]
I don't know if we have anything planned until the summer cycle (May 29th). Do you need any of this in sooner? We can create a new collection environment (collection-2018-1.2) and deploy it sooner.
(You'll have to activate it manually, just as a precaution: `BS_ENV=collection-2018-1.2 bsui` etc)

Let me know how urgent this is for you. thanks!

**Comment by CJ-Wright** [comment]
Oh, I thought you were interested in putting XPD on the internal conda standard.

**Comment by jrmlhermitte** [comment]
After discussion with CJ through hangouts, we decided that we'll deploy this next cycle. He has a local source install for this cycle. Thanks for the updates @CJ-Wright !

**Pull request merged**
