### PR TITLE
MNT:Add missing mds requirement to mdservice conda recipes

### PR DESCRIPTION
**Pull request by arkilic**
Attn @licode

### CODE REVIEW

**Comment by licode** [comment]
Looks good to me.

**Comment by arkilic** [comment]
Shld this update conda installation as soon as merged or you need to update the script?

**Comment by licode** [comment]
Installation with nsls2-dev will be updated immediately. But you need to put a new version in recipe in order to make nsls2-tag update.

**Comment by arkilic** [comment]
👍

**Pull request merged**
