### PR TITLE
eiger-io: remove filestore dependency

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you also bump the build number on both?

**Comment by mrakitin** [comment]
OK. Should I also tag a new version of the packages?
- https://github.com/NSLS-II-CHX/eiger-io/tags
- https://github.com/NSLS-II-CHX/chxtools/tags

**Comment by mrakitin** [comment]
@tacaswell?

**Comment by jrmlhermitte** [comment]
If I understand correctly, the build number forces a build? (is this true?)

Since we have a patch that may come in from [here](https://github.com/NSLS-II-CHX/eiger-io/pull/13)
should we hold off for one day and update the version then?

We could also tag chxtools with a later version number while we're at it since it's slightly behind master and we're going to test `eiger-io` at chx.

**Comment by mrakitin** [comment]
Done with version bumps. Also, updated the URL after transferring of the ownership of eiger-io to [NSLS-II](https://github.com/NSLS-II/eiger-io).

**Comment by mrakitin** [comment]
Also updated url/fn to git_url/git_rev for pychx.

**Comment by licode** [comment]
LGTM

**Comment by mrakitin** [comment]
Thanks for merging it, @licode!

**Pull request merged**
