### PR TITLE
Update metapackages for 2018C2.0

### PR DESCRIPTION
**Pull request by jrmlhermitte**
Should be merged after we're happy with most packages. should be done after #308  as well

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
Should I close this branch or will we use this Friday?

**Comment by danielballan** [comment]
I'm fine with using this Friday.

**Comment by jrmlhermitte** [comment]
changed version from RC to "0" thanks for the suggestion on slack @mrakitin 

Is there anything we want to add to this list? I vote for adding `kafka` to analysis and `bluesky-kafka` to collection.

**Comment by danielballan** [comment]
Confirmed on freyja that these build.

**Pull request merged**
