### PR TITLE
Bump event-model version to 1.8.0.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Does this have a numpy dependency?

**Comment by danielballan** [comment]
Yes. I should have added that. @mrakitin What is the best way to fix this these days?

**Comment by mrakitin** [comment]
@danielballan, do you want to re-tag? If so, we will remove the built/uploaded packages from both public and private conda channels.

**Comment by CJ-Wright** [comment]
You could patch it in the repodata.json

**Comment by mrakitin** [comment]
A new PR with the added dependency of `numpy` and the bumped build number would be sufficient, I suppose.

**Comment by mrakitin** [comment]
> @danielballan, do you want to re-tag? If so, we will remove the built/uploaded packages from both public and private conda channels.

I think I was wrong about re-tagging. The tag is there, it's just the new dependency.

**Pull request merged**
