### PR TITLE
SRX packages

### PR DESCRIPTION
**Pull request by mrakitin**
We just realized with @andrewmkiss that we are missing the analysis metapackage for SRX. I pushed the only extra package `pyxrf` manually, but with this PR we will push it automatically in the future.

### CODE REVIEW

**Comment by danielballan** [comment]
Is pyxrf now Python 3 compatible? At some point we had to put it in special Python 2 environments.

**Comment by licode** [comment]
py36 now. LGTM.

**Comment by mrakitin** [comment]
@danielballan, yes, it was successfully installed in our standard analysis-2019-1.2-srx environment. Great work on making it compatible with Python 3.6+, @licode.

**Comment by licode** [comment]
Thanks for adding this, @mrakitin . I should provide more update on pyxrf, so we can all stay at the same page without getting confused.

**Comment by mrakitin** [comment]
Cool, thanks for merging, @licode.

**Pull request merged**
