### PR TITLE
BLD: Move duplicate recipes to archive.

### PR DESCRIPTION
**Pull request by ke-zhang-rd**
```
atom
   lightsource2-defaults-2019-3.0
     0.2.3
     0.3.10
     0.3.2
     0.3.4
     0.3.5
     0.3.6
     0.3.7
     0.3.9
     0.4.0
     0.4.1
     0.4.3
   nsls2-tag
     0.3.10.post51
     0.4.0.dev
     0.4.0.dev.post0
```
I'm trying to archive atom of nsls2-tag as an example.
- [x] 1) archive them on lightsource2-recipes of github. Notice location change
- [x] 2) move them to archive channel on alexandria
- [x] 3) modify repodata.json on alexandria( I would be happy if there is some command to re-generate it)

### CODE REVIEW

**Comment by mrakitin** [comment]
Oh, actually the step 3 will be done automatically by the cron job running every 5 minutes to update the index. I agree on the first 2 steps.

**Comment by mrakitin** [comment]
I modified the description to make the items check-able. Please mark them when you are done with 1) and 2).

**Comment by ke-zhang-rd** [comment]
> Any ideas why `ppmac` was archived? I don't see a counterpart in the anaconda channel for that.

You are right.

**Comment by mrakitin** [comment]
I approve it as long as we have a good explanation regarding the `ppmac` package.

**Comment by tacaswell** [comment]
We may need to resurrect the gobject introspection to get hkl working....

**Pull request merged**
