### PR TITLE
channel archiver added

### PR DESCRIPTION
**Pull request by licode**
per @tacaswell  request.

### CODE REVIEW

**Comment by danielballan** [comment]
Do we want to package that NSLS-II fork instead? It is "8 commits ahead, 9 commits behind" the upstream branch. :- \ One of the fixes on our branch is py3 compat.

**Comment by danielballan** [comment]
Bump @licode @tacaswell

**Comment by tacaswell** [comment]
Definitely build from our version.

**Comment by danielballan** [comment]
This issue is blocking databroker + 3.6. It should be high-priority to support external collaboration here: https://github.com/NSLS-II/databroker/issues/140

**Comment by licode** [comment]
OK, I will change this to our nsls2 version.

**Comment by danielballan** [comment]
Notice that the latest commit on channelarchiver master includes py3-compat fixes and that the latest tag is several commits behind. Also, it almost looks like that tag is a typo (they go 0.0.4, 0.0.5, 0.0.5.6!). Maybe we should tag channelarchiver master as 0.0.6 and target this recipe at that.

**Comment by licode** [comment]
lets close this if there is no dependency on archiver?

**Comment by danielballan** [comment]
Sorry for the runaround, @licode.

**Pull request closed without merging**
