### PR TITLE
8 14 2018

### PR DESCRIPTION
**Pull request by CJ-Wright**
New xpd releases

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@tacaswell @stuartcampbell @danielballan @mrakitin I think this is ready for review/merge.
(On a side note would it be possible to make a team for reviewing these, that way I can ping the team?)

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by CJ-Wright** [comment]
It seems that the packages haven't been built yet (according to https://anaconda.org/lightsource2-tag) any idea what is happening?

**Comment by licode** [comment]
there are some issues on docker at backend. It should work now.

**Pull request merged**
