### PR TITLE
Add missing packages to the ISS analysis metapackage

### PR DESCRIPTION
**Pull request by mrakitin**
2 packages were missing during the latest push:
- pysmbc
- periodictable (probably it was never rebuilt with it)

### CODE REVIEW

**Comment by danielballan** [comment]
Is `pysmbc` a dependency of isstools in particular or of ISS in general? I recall [adding pysmbc as a dependency of isstools](https://github.com/NSLS-II/lightsource2-recipes/pull/74/files#diff-41f7bd321da4cb1a63643dc9f3c7c2f7R28) but it was subsequently [removed](https://github.com/NSLS-II/lightsource2-recipes/commit/1294b05cfd71f32bc2b4c9bc19218a94cf8dd1ee#diff-41f7bd321da4cb1a63643dc9f3c7c2f7L30).

**Comment by mrakitin** [comment]
Correct, it's used here: https://github.com/NSLS-II-ISS/isstools/blob/08e7d9c40591049839b4cd16d1feadc38a4e5b3a/isstools/xiaparser/xiaparser.py#L12.

I propose the following plan of actions:
- I will submit another PR to add pysmbc to the `isstools` package. We review/merge it, and wait until the package is pushed to anaconda.
- remove the dependency on pysmbc in this analysis metapackage. Will keep the new version number so that we have fresh packages with new `isstools`. Will merge and build it.
- merge #640, wait until it's built, push new envs with the updated dependencies.

**Comment by mrakitin** [comment]
Thanks for providing the references, @danielballan. Indeed, `pysmbc` was mistakenly removed from isstools in #614 during the major cleanup. #641 gets it back.

**Comment by mrakitin** [comment]
OK, new `isstools` is built. Time to merge before 3 pm iteration.

**Pull request merged**
