### PR TITLE
FIX: correct HDF5_PLUGIN_PATH to use $CONDA_PREFIX

### PR DESCRIPTION
**Pull request by mrakitin**
Based on conversation in Slack.

### CODE REVIEW

**Comment by danielballan** [comment]
Context for future reference: it seems like conda changed the name of this env var under us. Have not confirmed that, but this works.

**Comment by jrmlhermitte** [comment]
:+1:

**Comment by mrakitin** [comment]
Thanks!

**Comment by tacaswell** [comment]
I am just going to delete the current package from both the public and private channels (or it won't build!)

**Pull request merged**
