### PR TITLE
Bugfix version update

### PR DESCRIPTION
**Pull request by dhidas**
Fix for importing arbitrary function as efield.

### CODE REVIEW

**Comment by licode** [comment]
Thanks for the update. But I will close this, and further simply this recipe. Because the current recipe still needs sha value. I will send a PR to review.

**Comment by licode** [comment]
@dhidas  Your github shows the release the number is 2.00.04. https://github.com/dhidas/OSCARS/tags
That's the number used to build, instead of 2.04. Is this ok? 

We can build 2.02 previously because the recipe searched source from pip which has 2.02. But now we want it to search github release.

**Comment by dhidas** [comment]
It seems better to keep the numbering the same.  I tagged 2.0.4 in github and will keep with this scheme without zfill.  Seem fine to you?

**Comment by licode** [comment]
ok, I will update the version to 2.0.4.

**Pull request closed without merging**
