### PR TITLE
MNT: boltons are removed

### PR DESCRIPTION
**Pull request by licode**
Done.

### CODE REVIEW

**Comment by tacaswell** [comment]
I think bluesky still uses boltons.

**Comment by licode** [comment]
OK, I thought you wanted it to be deleted from any places.

**Comment by licode** [comment]
Added it back.

**Comment by tacaswell** [comment]
Only on the projects that do not actually have it as a dependency any more.

You can quickly check if a project uses it by `git grep boltons` in the source tree.

**Comment by licode** [comment]
Right, that's what I am doing.

**Comment by arkilic** [comment]
databroker also uses boltons [here](https://github.com/NSLS-II/databroker/blob/0365af849a3ef5fa0e8d254bff72c3c3a1da2f37/databroker/core.py#L585)

**Comment by licode** [comment]
Filestore also needs that. So only remove boltons from metadatastore.

**Comment by licode** [comment]
ready to go? anyone?

**Comment by arkilic** [comment]
Closes #38

**Pull request merged**
