### PR TITLE
event-model: make it 3.6+

### PR DESCRIPTION
**Pull request by mrakitin**
To mirror the changes in https://github.com/conda-forge/event-model-feedstock/pull/10 as event-model 1.8.2 is Python 3.6+ (https://github.com/NSLS-II/event-model/pull/51). See discussion in Slack with @CJ-Wright for details.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This worked on CF

**Comment by mrakitin** [comment]
Awesome! Thanks for pointing out to this problem, @CJ-Wright!

**Comment by CJ-Wright** [comment]
No problem. I feel a bit sheepish since I was the one who merged the broken CF PR :sheep:

**Comment by mrakitin** [comment]
Weird, it now does not want to build for Python 3.6:
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from argument_variants
Adding in variants from internal_defaults
Adding in variants from argument_variants
True     | linux-64/event-model-1.8.2-py>=36_1.tar.bz2
INFO:build.py:True     | linux-64/event-model-1.8.2-py>=36_1.tar.bz2
dependency_graph=<generator object resolve_dependencies at 0x7f8b14539930>
Build Order.
INFO:build.py:Build Order.
linux-64/event-model-1.8.2-py>=36_1.tar.bz2
INFO:build.py:linux-64/event-model-1.8.2-py>=36_1.tar.bz2
Building: linux-64/event-model-1.8.2-py>=36_1.tar.bz2
INFO:conda_build.metadata:Attempting to finalize metadata for event-model
Attempting to finalize metadata for event-model
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['event-model-1.8.2-py37_1.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
```

**Comment by CJ-Wright** [comment]
Ah you might need to make this an arched package, idk if the conda-build you are on will support that.

**Comment by mrakitin** [comment]
We are on the latest one now (3.17.8). What change is needed here?

**Comment by CJ-Wright** [comment]
Ah sorry, I was confused. It will build on the latest python available and within the constraints. Since this is noarch it will work with py36 as well.

**Comment by mrakitin** [comment]
Oh, I think we should limit the Python version only for the `run` section of the recipe. That way it will be built successfully with the existing Python, but will require the correct version during the installation. I'll submit a separate PR for the change.

**Pull request merged**
