### PR TITLE
Revive HKL

### PR DESCRIPTION
**Pull request by mrakitin**
This was built successfully using https://hub.docker.com/r/mrakitin/debian-with-miniconda/tags/ (20181116161941) and the existing recipe for `hkl`.

### CODE REVIEW

**Comment by licode** [comment]
If you check dependencies, I think this building of hkl uses pygobject3 ==3.18.2 and glib=2.51. But all our stack is based on glib=2.56, that's why this hkl can't be installed.

**Comment by mrakitin** [comment]
Let's try a newer version of pygobject v3.31.1, which has a different installation method (`python setup.py install`). I built is successfully locally, it's pushed to https://anaconda.org/lightsource2-tag/pygobject/3.31.1/download/linux-64/pygobject-3.31.1-py36_0.tar.bz2.

**Comment by licode** [comment]
great. let's have a try! new version may help.

**Comment by licode** [comment]
good job. The new version is only there for 2 days. http://ftp.acc.umu.se/pub/GNOME/sources/pygobject/

Let's see.

**Pull request merged**
