### PR TITLE
pycentroids: try to build v0.1.8 again

### PR DESCRIPTION
**Pull request by mrakitin**
~https://github.com/NSLS-II/lightsource2-recipes/pull/739~ (wrong reference) #745 did not seem to go through on freyja. Try it again.

### CODE REVIEW

**Comment by mrakitin** [comment]
Got this error:
```
CMake Error at python/CMakeLists.txt:11 (find_package):
  By not providing "Findlmfit.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lmfit", but
  CMake did not find one.

  Could not find a package configuration file provided by "lmfit" with any of
  the following names:

    lmfitConfig.cmake
    lmfit-config.cmake

  Add the installation prefix of "lmfit" to CMAKE_PREFIX_PATH or set
  "lmfit_DIR" to a directory containing one of the above files.  If "lmfit"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
@stuwilkins, do you have any ideas where it comes from? Should we tag a newer version of `lmfit-c`?

**Comment by stuwilkins** [comment]
Hi ... is the lmfit-c package installed?

**Comment by stuwilkins** [comment]
@mrakitin once #823 is merged, this should build ok. I verified on my system that it does. The issue is that between 0.1.7 and 0.1.8 I used `cmake` to find the `lmfit-c` package and had revved this. 

Thinking about it, for now SIX might be better to be on master (dev) for both `pycentroids` and `lmfit-c`

**Comment by mrakitin** [comment]
It worked! Thanks for the help, @stuwilkins!

**Pull request merged**
