### PR TITLE
CHX: fix dependencies for collection-2018-1.0

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Comment by licode** [comment]
thanks for updating this. @danielballan recommended before to use playbooks to store all the beamline collection instead of here, maybe let's double check with him on this?

**Comment by jrmlhermitte** [comment]
I tried to build and I get:
Error: bad character '\' in package/version: 2018\-1.0

@licode is there a way to keep dashes?

**Comment by tacaswell** [comment]
I suspect not, as conda uses `-` for sematic separation.  I would go with `.` or `C`

**Comment by jrmlhermitte** [comment]
Ok. I have two PR's to make for two different extra packages. Can we agree that "c" is the convention used?
So `2018C1.0`? thanks!

**Comment by mrakitin** [comment]
Changed dash to underscore until we decide what's a better symbol ('C' or '_').

**Comment by jrmlhermitte** [comment]
Can we vote on this and decide?
:+1: - `_`
:-1: - `C`

**Comment by mrakitin** [comment]
OK, updated to `C` :)

**Comment by jrmlhermitte** [comment]
looks good, also built again just in case..... so looks like it's "C" merging! :-)

**Comment by mrakitin** [comment]
Great, thanks for reviewing and merging!

**Pull request merged**
