### PR TITLE
ENH: add hdf5-lz4 as a dependency for eiger-io

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Comment by danielballan** [comment]
I don't think eiger-io is usable without hdf5-lz4, but would like a sanity check from @jrmlhermitte on this, given his CHX experience.

**Comment by danielballan** [comment]
Strictly speaking, Eiger might not always compress with LZ4 but in practice at NSLS-II it always does, and this is mostly a facility-specific package at this point, so we are take the pragmatic approach.

If you discover this PR someday and have a reason to want it out, ask!

**Comment by danielballan** [comment]
Shoot -- forgot to bump that build number. Can you submit a new PR, @mrakitin?

**Comment by mrakitin** [comment]
Done, see #270.

**Pull request merged**
