### PR TITLE
Move ophyd into 'analysis' metapkg so that bluesky.examples works.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by mrakitin** [comment]
Do we need to bump a build number here? Or remove the already built packages from anaconda and our local channels.

**Comment by danielballan** [comment]
Let's remove the old ones.

**Comment by danielballan** [comment]
(I'm on it.)

**Comment by mrakitin** [comment]
Sounds good! Merging to trigger new builds.

**Pull request merged**
