### PR TITLE
chxtools: fix git_url & git_rev

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
Looks good but file appears to have executable permissions. Could you quickly fix that?

**Comment by mrakitin** [comment]
Good catch! Done.

**Comment by jrmlhermitte** [comment]
Looks good. Did you try building?
`conda build -c lightsource2-tag meta.yaml`

It seems to go through except I eventually get:
```python
conda.exceptions.ResolvePackageNotFound: 
  - nslsii_dev_configuration
```

but not sure if this is just me. @licode Any idea? I'm likely doing something wrong (but this has worked for previous packages)

**Comment by jrmlhermitte** [comment]
Oops!!! I typed ` conda build -c conda-forge meta.yaml` and not `lightsource2-tag`!
Please ignore that comment! Looks good, merging... thanks @mrakitin !

**Comment by mrakitin** [comment]
Thanks!

**Pull request merged**
