### PR TITLE
xpd cycle 2 2018

### PR DESCRIPTION
**Pull request by CJ-Wright**
I have one more on the way but I'll most likely get it in first thing tomorrow.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Attn: @chiahaoliu

**Comment by CJ-Wright** [comment]
I think this is ready to go! @licode @mrakitin

**Comment by mrakitin** [comment]
Looks good to me, thanks.

**Comment by mrakitin** [comment]
@CJ-Wright, any ideas?

**Comment by CJ-Wright** [comment]
What version of conda build are you using?

**Comment by mrakitin** [comment]
Tried 3 times on different machines, same failure.
Conda build's version is `conda-build-3.1.6`

**Pull request merged**
