### PR TITLE
Rebuild HKL library

### PR DESCRIPTION
**Pull request by mrakitin**
# Please review carefully, many changes!

## What we don't need to build
After a few attempts to build the stack I realized we don't need to build the following packages (originally found in https://github.com/ericdill/hkl-conda/blob/master/install):
- [glib](https://ftp.gnome.org/pub/gnome/sources/glib/2.56/) (comes from `defaults`)
- [cairo-gobject](https://www.cairographics.org/releases/) (this comes from `defaults` as cairo)
- [gsl](https://ftp.gnu.org/gnu/gsl/) (also comes from `defaults`)

## What we **do** need to build
- [gobject-introspection](http://ftp.acc.umu.se/pub/gnome/sources/gobject-introspection/1.56/) - the recipe is based on https://github.com/conda-forge/gobject-introspection-feedstock/tree/master/recipe with removal of the test section in `build.sh` (it constantly failed with the `libpng16.la not found` error)
- [hkl](https://github.com/picca/hkl) - minor modifications to use pygobject instead of pygobject3
- [hklpy](https://github.com/NSLS-II/hklpy) - same as above

## Other changes
Cleaned some messy packages with version numbers to avoid future confusion:
- `cairo-gobject-1.12.18`
- `gobject-introspection-1.47.1`
- `hkl-v5.0.0.2080`
- `py3cairo-1.10.0`

## How it was tested:
- started a docker container with `docker run -it --rm mrakitin/debian-with-miniconda bash`
- cloned this repo and checked out my PR branch
- cd to `lightsource2-recipes/recipes-tag/` and built the packages with `conda build gobject-introspection/ hkl/ hklpy/`
- created a new conda env with Python 3.6 and `collection=2018C3.3` and installed the locally built packages *with dependencies* (https://github.com/conda/conda/issues/1884#issuecomment-332852486):
```bash
conda install -c local gobject-introspection hkl hklpy
```
- it looks to be imported fine in IPython:
```py
(collection-2018-3.3) root@7bdba9fabd56:~/lightsource2-recipes/recipes-tag# ipython
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import gi

In [2]: import hkl

In [3]: import hkl.calc
/conda/envs/collection-2018-3.3/lib/python3.6/site-packages/hkl/util.py:9: PyGIWarning: Hkl was imported without specifying a version first. Use gi.require_version('Hkl', '5.0') before import to ensure that the right version gets loaded.
  from gi.repository import Hkl as hkl_module

In [4]: import hkl.context

In [5]: import hkl.diffract

In [6]: import hkl.engine
...
In [8]: import hkl.sample

In [9]: import hkl.util

In [10]: hkl.diffract.Diffractometer
Out[10]: hkl.diffract.Diffractometer

In [11]: hkl.diffract.Diffractometer?

In [12]: hkl.calc
Out[12]: <module 'hkl.calc' from '/conda/envs/collection-2018-3.3/lib/python3.6/site-packages/hkl/calc.py'>

In [13]: hkl.calc.CalcParameter
Out[13]: hkl.engine.CalcParameter

In [14]: hkl.calc.CalcParameter?
Init signature: hkl.calc.CalcParameter(param, geometry, *args, **kwargs)
Docstring:      <no docstring>
Init docstring:
Like calc parameter but needs reference to a geometry object.
Updates to the parameter should be propagated back to the geometry.

Parameters
----------
    param : HklParameter
    geometry: Geomery object
File:           /conda/envs/collection-2018-3.3/lib/python3.6/site-packages/hkl/engine.py
Type:           type

In [15]:
```

### A side note:
It seems the latest changes to ophyd broke hklpy, so I observe this error when loading https://github.com/NSLS-II-CSX/xf23id1_profiles_simulated:
```py
/conda/envs/collection-2018-3.3/lib/python3.6/site-packages/ophyd/device.py in create_component(self, instance)
    137             cpt_inst = self.cls(pv_name, parent=instance, **kwargs)
    138         else:
--> 139             cpt_inst = self.cls(parent=instance, **kwargs)
    140
    141         if self.lazy and hasattr(self.cls, 'wait_for_connection'):

TypeError: __init__() got an unexpected keyword argument 'kind'
```

### CODE REVIEW

**Comment by licode** [comment]
Great work! I got some quick questions: 

Any reason not to use gobject-introspection from defaults, https://anaconda.org/anaconda/gobject-introspection ?

pygobject is still from old version?

Can you also run tests with pyepics, bluesky and mpl?

**Comment by licode** [comment]
Sure. I am working on test.

**Comment by mrakitin** [comment]
> Great work! I got some quick questions:
> 
> Any reason not to use gobject-introspection from defaults, https://anaconda.org/anaconda/gobject-introspection ?
> 
> pygobject is still from old version?
> 
> Can you also run tests with pyepics, bluesky and mpl?

@licode, there was a problem during the build process of `hkl` is the stock `gobject-introspection` package from `defaults` was used, it resulted in the same problem you observed yourself - the missing `libdummy.la` library. I had to rebuild it to make it work for `hkl`.

**Comment by mrakitin** [comment]
I think the PR is ready for merge. Any subsequent updates can be done in separate PRs. Let's have those packages available in our public channel first.

**Comment by mrakitin** [comment]
Thanks for merging, @licode!

**Comment by licode** [comment]
This is awesome. We get hkl ready!

**Pull request merged**
