### PR TITLE
Add dask-related deps.

### LINKED ISSUE #203: Add dask, distributed, graphviz, python-graphviz.

### PR DESCRIPTION
**Pull request by danielballan**
Closes #203

### CODE REVIEW

**Comment by danielballan** [comment]
This should have gone in before we created the new envs. Probably worth remaking the envs. :-\

**Comment by jrmlhermitte** [comment]
:+1:

**Comment by tacaswell** [comment]
this needs a rebas

**Comment by jrmlhermitte** [comment]
what's the status on this?

**Comment by mrakitin** [comment]
Conflicting `graphviz` dependency.

**Comment by jrmlhermitte** [comment]
@danielballan can you rebase?

**Comment by jrmlhermitte** [comment]
this looks good to me

**Pull request merged**
