### PR TITLE
BLD: rc3

### PR DESCRIPTION
**Pull request by ke-zhang-rd**

### CODE REVIEW

**Comment by mrakitin** [comment]
Does `intake` install file into the rc1 environment?

**Comment by ke-zhang-rd** [comment]
> Does `intake` install file into the rc1 environment?

No

**Comment by mrakitin** [comment]
I meant the new `intake` in our channel produced by #718.

**Comment by mrakitin** [comment]
This was merged after successful test of installing `intake` from `lightsource2-tag` into the `rc1` test environment. Communicated via PM in Slack with @ke-zhang-rd.

**Pull request merged**
