### PR TITLE
analysis-2019C3.0.1 metapackage

### PR DESCRIPTION
**Pull request by mrakitin**
A mirror update of https://github.com/nsls-ii-forge/analysis-feedstock/pull/6. See the test results for Python 3.6/3.7 and Linux/OSX/Windows in that PR (kind of naive integration testing).

### CODE REVIEW

**Comment by mrakitin** [comment]
Please note, the PR should be merged only after #776 is reviewed/merged, and the corresponding packages have been built.

**Comment by mrakitin** [comment]
Also, it needs https://github.com/NSLS-II/lightsource2-recipes/pull/780.

**Comment by danielballan** [comment]
#776 and #780 are merged. Waiting for packages to build.

**Comment by mrakitin** [comment]
Thanks, @danielballan! The suitcases and event-model have been built and uploaded. Please go ahead with merging this PR.

**Pull request merged**
