### PR TITLE
Added pycentroids and dependency (lmfit-c)

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by stuwilkins** [comment]
@danielballan I think this is what you mentioned to do by e-mail. This is to add `pycentroids` for SIX.

**Comment by stuwilkins** [comment]
Just tested with the `/opt/conda_envs/analysis-2018-3.2` kernel on `xf02id1-srv1` using manual install. Both packages install ok.

**Comment by stuwilkins** [comment]
Added `cpplint` for C/CXX code style checking.

**Comment by stuwilkins** [comment]
Thanks @danielballan !!

@mrakitin, @ke-zhang-rd Happy to change anything into DAMA standards, please review when you have a chance. Thanks!

**Comment by mrakitin** [comment]
> This looks good to me, thanks @stuwilkins! I tested it locally, the both packages build fine.

Actually, there are 3 packages + 1 metapackage there. `lmfit-c`, `pycentroids` and `pycentroids` are built fine.

**Comment by stuwilkins** [comment]
Thanks @mrakitin Yes I wanted to pin the lmfit at `8.2.2.post27`. Its not my lib so I didn't want to advance the version number, but just have a version which is defined, that is why it is pinned to a git hash.

**Comment by mrakitin** [comment]
Great, thanks for the explanation!

**Comment by mrakitin** [comment]
For some weird issue there is the following error appearing for `lmfit-c`:
```
Compressing to /tmp/tmpgk2zxdha/lmfit-c-8.2.2.post27-10.tar.bz2
Error: Failed to render jinja template in /repo/recipes-tag/lmfit-c/meta.yaml:
'dict object' has no attribute 'GIT_DESCRIBE_TAG'
```
I don't see this error when I build locally in the same Docker container (`nsls2/debian-with-miniconda:latest`). I think it can be changed from `environ.GIT_DESCRIBE_TAG` -> `environ['GIT_DESCRIBE_TAG']`.

**Pull request merged**
