### PR TITLE
DEV: version update for collection and analysis

### PR DESCRIPTION
**Pull request by licode**

### CODE REVIEW

**Comment by tacaswell** [comment]
`YYQCC.N` would be terser, but we may not want to mess with the existing scheme so they continue to sort in the correct order.

**Comment by licode** [comment]
Can we use build number 0, 1, 2 for different versions?
build:
  number: 0

**Comment by tacaswell** [comment]
different builds of the same version should be semantically interchangeable, the minor version bumps will not be.

**Comment by licode** [comment]
good to know. thanks.

**Pull request merged**
