### PR TITLE
different folder for condaforge recipes

### PR DESCRIPTION
**Pull request by licode**

### CODE REVIEW

**Comment by licode** [comment]
anything else from cf? @tacaswell

**Comment by licode** [comment]
pyfai, slicerator

**Comment by danielballan** [comment]
This should wait for the next cycle now -- probably want to avoid creating chaos at this point.

**Comment by tacaswell** [comment]
Why do pyfai, slicerator, pympler get completely deleted?

**Comment by licode** [comment]
closed. not implemented soon.

**Pull request closed without merging**
