### PR TITLE
2018C3.0 for csx1

### PR DESCRIPTION
**Pull request by licode**

### CODE REVIEW

**Comment by danielballan** [comment]
Are those new _direct_ dependencies at CSX? If they are actually secondary dependencies, pulled in through hklpy, it would be better to update the hlkpy recipe and then bump the hlkpy pin here.

**Comment by danielballan** [comment]
To explain why a bit more: by updating hlkpy itself, these updated requirements will automatically propagate to _all_ beamlines that need it, rather than requiring us to keep many metapackages in sync manually.

**Comment by licode** [comment]
those are deps on hkl. Basically no change needed here I think.

**Comment by danielballan** [comment]
It would be best if we could pin this such that we are sure that we get a build of hklpy that has the seconardy deps that we want. But we can circle back to that question once you have update the hklpy recipe.

**Comment by licode** [comment]
close it for now. reopen when hkl is ready.

**Pull request closed without merging**
